### ISSUE TITLE
bot died 

### ISSUE THREAD

**Issue by Nedwi-ID** [KhanhNguyen9872/python3-obf#1]
your *obfuscator* telegram bot has been died.
Maybe It's hard to maintain. You can Upload the obfuscator on Github [ without source ] . By the way that was the best.

**Comment by KhanhNguyen9872** [comment]
> your _obfuscator_ telegram bot has been died. Maybe It's hard to maintain. You can Upload the obfuscator on Github [ without source ] . By the way that was the best.

bot working now
